### ISSUE TITLE
termios.error on connection lost

### ISSUE THREAD

**Issue by slavkoja** [pyserial/pyserial-asyncio#12]
Hi,

I am not sure where to report this, if here or to pyserial, but i am sure, that you will know what to do with it...

While playing with `pyserial.aio` and try to build serial server, which waits for USB/UART adapter to be connected, then process incoming data and if the connection will lost, then again wait for adapter. I start with base example there with virtual serial port (created via `socat`) and all seems to work, except situation when i simulate connection lost (exit the `socat`), where i got exception, which i was not able to catch:

```python
Exception in callback SerialTransport._call_connection_lost(SerialExcepti...s on port?)',))
handle: <Handle SerialTransport._call_connection_lost(SerialExcepti...s on port?)',))>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/serial/aio.py", line 346, in _call_connection_lost
    self._serial.flush()
  File "/usr/lib64/python3.4/site-packages/serial/serialposix.py", line 550, in flush
    termios.tcdrain(self.fd)
termios.error: (5, 'Input/output error')
```
This exception causes, that the `loop` is not closed inside the `connection_lost` method in `Output` class (because it is not called at all), the connection stays open and when the port is created again, it is not more connected to program.

After small investigation in the `/usr/lib64/python3.4/site-packages/serial/aio.py` file (from `pyserial` 3.1.1 on my Funtoo Linux) i found that in the `_call_connection_lost` (the `SerialTransport` class) is called `self._serial.flush()`, where exception occurs (because there is no more this port in system). After i changed the line 345:
```python
self._serial.flush()
```
to ignore this exception (because it is expected):
```python
try:
    self._serial.flush()
except termios.error:
    pass
```
(and appropriate `import termios` of course) all seems to work as expected, i.e. the `connection_lost` method of the `Output` class is called and loop is closed.

I am not Python nor pyserialúasyncio expert, then i am not sure if this is solution or workaround, but i see that similar solution is

**Comment by rob-smallshire** [comment]
Thank you for the detailed report.  If you use the latest version of pyserial-asyncio from here or from PyPI you should find that this problem has already been been fixed, using exactly the same approach you used. The older version of the code you were using that was packaged in `pyserial.aio` did not have this fix. So,

    pip install pyserial-asycio

update your imports, and everything should work
