### ISSUE TITLE
Push changes to pypi

### ISSUE THREAD

**Issue by riggs** [pyserial/pyserial-asyncio#14]
The latest version of this library [currently on pypi (0.2)](https://pypi.python.org/pypi/pyserial-asyncio/0.2) crashes if you pass the 'loop' keyword to `serial.aio.open_serial_connection`. This is fixed in the current master.

**Comment by rob-smallshire** [comment]
Hi @zsquareplusc can you do this?  I don't have the necessary rights with PiPI.

**Comment by zsquareplusc** [comment]
OK, done
