### ISSUE TITLE
Serial rts on connection made

### ISSUE THREAD

**Issue by iiSeymour** [pyserial/pyserial-asyncio#16]
On connection made rts is set to False, is there a reason for doing so? 

    def connection_made(self, transport):
        self.transport = transport
        print('port opened', transport)
        transport.serial.rts = False
        transport.write(b'hello world\n')

**Comment by iiSeymour** [comment]
Yes, it's in the example, tests and documentation, I wasn't sure why it would be necessary.

I've written a small client using the transport protocol based of the example and I've tried playing with the reader, writer interface without luck. Would it be possible to add an example of using `open_serial_connection`, for instance how do you pass in the `port` to connect to?

**Comment by zsquareplusc** [comment]
It looks like you are using the asyncio feature formerly available as `serial.aio`. The latest functionality is available via [pyserial-asyncio](https://github.com/pyserial/pyserial-asyncio), so the discussion about this should be moved over there.

**Comment by iiSeymour** [comment]
Over there is over here, right? This issue is under `pyserial-asyncio`.

**Comment by zsquareplusc** [comment]
oops, right... here :-)

**Comment by rob-smallshire** [comment]
Fixed by c7228d I've added an explanatory comment to the example in question.
