### ISSUE TITLE
Socket support

### ISSUE THREAD

**Issue by iiSeymour** [pyserial/pyserial-asyncio#17]
When passing in `socket://127.0.0.1:9999` as port to `create_serial_connection` to connect an [EchoServerClientProtocol](https://docs.python.org/3/library/asyncio-protocol.html#tcp-echo-server-protocol) an `AttributeError` is thrown on accessing `self._serial.fd`.

```
File "/usr/local/lib/python3.5/site-packages/serial/aio.py", line 260, in _ensure_reader
    self._loop.add_reader(self._serial.fd, self._read_ready)
AttributeError: 'Serial' object has no attribute 'fd'
```

**Comment by rob-smallshire** [comment]
As you have discovered pyserial-asyncio has not been tested in this scenario. It looks like the uses of `self._serial.fd` by pyserial-asyncio should be replaced by `self._serial.fileno()` which is supported by both the regular Posix and socket based Serial implementations, although curiously, not by the RFC2117 implementation.
