### ISSUE TITLE
Should we use pyserial-asyncio or the aio built into pyserial?

### ISSUE THREAD

**Issue by cmcqueen** [pyserial/pyserial-asyncio#22]
I see that [pyserial has "experimental asyncio support"](https://pythonhosted.org/pyserial/pyserial_api.html#module-serial.aio). Which is better to use—that or this project?

**Comment by rob-smallshire** [comment]
pyserial-asyncio supersedes and replaces pyserial.aio. You should use pyserial-asyncio.

**Comment by cmcqueen** [comment]
Please don't close this yet...

I asked this question as an issue, because it's not clear from the documentation of either pyserial or pyserial-asyncio. So, could you please update the documentation of either or both, to clarify that pyserial-asyncio supersedes and replacess pyserial.aio.

**Comment by slavkoja** [comment]
@cmcqueen , you are right that this is slightly confusing situation and the @rob-smallshire could be more communicative. But when you take look at [pySerial-asyncio API](http://pyserial-asyncio.readthedocs.io/en/latest/api.html) and #21, you can see, that it clearly describes usage of ``pyserial-asyncio`` module.

The ``aio`` module was removed from recent versions of ``pyserial`` (i am not sure about exact version now), but it was included in some 3.x releases then it is described there (and confuses). IMO this was closed properly here and if you want, you can/need fill something about it into ``pyserial`` directly, to improve its documentation.

**Comment by cmcqueen** [comment]
Thanks, good point.

**Comment by thatch** [comment]
The doc removal still has not been pushed to pythonhosted.
