### ISSUE TITLE
Streams (coroutine based API) support

### ISSUE THREAD

**Issue by DurandA** [pyserial/pyserial-asyncio#25]
Is the support of *awaitable* [`Streams API`](https://docs.python.org/3/library/asyncio-stream.html) in addition to the [`Protocol`](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.Protocol) (callback-based API) planned or already included?

**Comment by lbonn** [comment]
It's there already, with `open_serial_connection`: https://github.com/pyserial/pyserial-asyncio/blob/4f58e9ba032262747605c9f64afe036c23173ae1/serial_asyncio/__init__.py#L417

For some reason, it does not appear in the official documentation.

**Comment by rob-smallshire** [comment]
The documentation definitely needs improvement in this regard. Let's keep this issue open to track that.

**Comment by mkmk88** [comment]
Could you please write an example of open_serial_connection usage? I'm struggling with passing correct arguments there.

**Comment by Jeremy-Usbourne** [comment]
I second the request for a streams example. Thanks.

**Comment by d21d3q** [comment]
[Here](https://github.com/riptideio/pymodbus/blob/657812124ebbbbdbee8188bee7df50120f92f379/examples/contrib/asynchronous-asyncio-serial-client.py) is working example with modbus. 
it is done in regular function but in async one you can: 
```python
transport, protocol = await create_serial_connection(loop, make_protocol, '/dev/ttyUSB0', baudrate=9600)
```

**Comment by rob-smallshire** [comment]
#63 documents the existing streams support which has been present for a long time.
