### ISSUE TITLE
Improve the API design of create_serial_connection

### ISSUE THREAD

**Issue by rob-smallshire** [pyserial/pyserial-asyncio#27]
The implementation of `create_serial_connection` currently creates the `Serial` object, forwarding the `*args` and `**kwargs` parameters. A more flexible design would be to allow a `Serial` instance to be passed in by the caller.

**Comment by stxlvt** [comment]
I'm considering using pyserial-asyncio, but I need `create_serial_connection` to instantiate a subclass of Serial that I've written, instead of the default implementation.

Of course, `create_serial_connection` is a short function, so it's no problem to copy and modify its code to use a different class to make the serial object, and this makes for a quick and easy solution.

But since this issue is about API design I would like to support this idea, or some other mechanism that avoids the (albeit small) DRY violation that I'm forced to commit with the current API design.

**Comment by zsquareplusc** [comment]
a workaround would be to install a [protocol handler](http://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.protocol_handler_packages) in pySerial and then use the URL form to open the port (see previous link for more details)

a module can either provide a `serial_class_for_url(url)` method or `Serial` class.
[examples](https://github.com/pyserial/pyserial/tree/master/serial/urlhandler)

**Comment by stxlvt** [comment]
@zsquareplusc You're right of course, but that's *way* more work to get up and running than simply creating a personalized version of the `create_serial_connection` function, which would take less than a minute and would not require browsing docs and examples.

Installing a protocol handler is also less flexible, as it requires the url form for it to work. Finally, it feels like I'm using it for something slightly different from its intended purpose -- I don't really want to implement a new kind of protocol or url scheme, I just want to take advantage of the Liskov Substitution Principle and use a custom subclass of Serial.

**Comment by rob-smallshire** [comment]
Here's my proposal: We introduce a new function, `connection_for_serial()` which allows the `Serial` instance to be provided as an argument:

    @asyncio.coroutine
    def connection_for_serial(loop, protocol_factory, serial_instance):
        protocol = protocol_factory()
        transport = SerialTransport(loop, protocol, serial_instance)
        return (transport, protocol)

We then refactor `create_serial_connection()` to be implemented in terms of this new function, so we can both avoid duplication, and retain compatibility for existing users:

    @asyncio.coroutine
    def create_serial_connection(loop, protocol_factory, *args, **kwargs):
        serial_instance = serial.serial_for_url(*args, **kwargs)
        return (yield from connection_for_serial(loop, protocol_factory, serial_instance))

The parameter name `serial_instance` is used to avoid hiding the name of the `serial` module.
