### ISSUE TITLE
Handling Input/output error

### ISSUE THREAD

**Issue by Kaveshnikov** [pyserial/pyserial-asyncio#28]
Hello,
I've tried to use the example from the documentation to get data from my device and got an error, when I plug out the usb cable. At the same time, the main loop continues. How can I handle this error?

Traceback
```
Exception in callback SerialTransport._call_connection_lost(SerialExcepti...s on port?)',))
handle: <Handle SerialTransport._call_connection_lost(SerialExcepti...s on `port?)',))>`
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/dist-packages/serial/aio.py", line 345, in _call_connection_lost
    self._serial.flush()
  File "/usr/local/lib/python3.5/dist-packages/serial/serialposix.py", line 578, in flush
    termios.tcdrain(self.fd)
termios.error: (5, 'Input/output error')
```

**Comment by rob-smallshire** [comment]
Are you using the latest code from here on GitHub?  The `termios.error` being raised on unplugging should be handled and ignored by the existing implementation. See:

https://github.com/pyserial/pyserial-asyncio/blob/master/serial_asyncio/__init__.py#L396

**Comment by Kaveshnikov** [comment]
Yes, my mistake. I used version from serial.aio. Thanks.
