### ISSUE TITLE
Consider support for trio

### ISSUE THREAD

**Issue by zmitchell** [pyserial/pyserial-asyncio#35]
Hi, I’ve been using `pyserial-asyncio` for a little bit now, and I have a suggestion. Right now the library is implemented on top of `asyncio`, but the result is that you don’t get a single file-like object to interact with as you do in the synchronous case.

I’ve recently been looking at [`trio`](https://github.com/python-trio/trio) which is an async framework inspired by David Beazley’s `curio`. Neither are built on `asyncio`, but `trio` especially looks much easier to use than `asyncio`. There is a ton of fantastic documentation that comes with `trio`, and there's a ton of testing/debugging/introspection facilities.

To give you an idea of how nice `trio` is to use, it provides a function `trio.wrap_file()` which takes a file-like object and returns another file-like object whose `read`, `write`, etc methods are all awaitable (you can still get to the non-file attributes through `foo.wrapped.bar`). In fact, I used this function to wrap a `Serial` instance, and in most cases it seems to work just like a natively async `Serial` class would. The `wrap_file()` function actually uses threads to do this, and as a result there are some edge cases where the wrapped object can become unresponsive. That’s why I’m requesting a `trio`-native `Serial` class.

What are your thoughts?

**Comment by rob-smallshire** [comment]
I don't have first-hand experience of trio. This is pyserial-asyncio. It seems like there's room for a pyserial-trio as a separate project.
