### ISSUE TITLE
Support for rs485

### ISSUE THREAD

**Issue by Alkaselzer22** [pyserial/pyserial-asyncio#37]
Hi there! I am currently working on migrating a real-time communications program from sync Python2.7 to async Python3.7. This program manages mobile radio devices via serial; each one with a different set of settings. The only thing that I'm missing right now is support for rs485 serials. PySerial has a 'rs485 mode' implementation, but I haven't seen anything about it on this library. 

Is there any way to work around this (maybe a wrap around serial.rs48.RS485)?

Thanks,

**Comment by rob-smallshire** [comment]
pyserial-asyncio can use whichever Serial instance you provide if you establish the connection with `connection_for_serial(loop, protocol_factory, serial_instance)`. Create and configure your `Serial` instance as necessary using regular pySerial and then pass that instance to this function.
