### ISSUE TITLE
connection lost - why?

### ISSUE THREAD

**Issue by bsdis** [pyserial/pyserial-asyncio#39]
Hi, 
Thank you for working on this very nice library.

I tried copying the example from here: https://pyserial-asyncio.readthedocs.io/en/latest/shortintro.html and changed the baudrate etc. 
The serial port is connected to an arduino uno running grbl and when i use the normal pyserial library this behaves as expected.
But when I run that sample program - the serialport is connected, I get some feed back from the arduino board (not all) and then the program just closes - see below

$ python serialaio.py 
port opened SerialTransport(<_UnixSelectorEventLoop running=True closed=False debug=False>, <__main__.Output object at 0x1058bd4a8>, Serial<id=0x1058bd278, open=True>(port='/dev/cu.usbmodem1411', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=0, xonxoff=False, rtscts=False, dsrdtr=False))
data received b'\r\nG'
port closed

Is this caused by some bug in the pyserial-aio library or is it something else?

Thank you in advance

P.S.
I am running this on a macos, using python 3.6 and serial_asyncio v. 0.4

**Comment by pszafer** [comment]
I have exact same problem with pyserial-asyncio.
Regular pyserial is receiving data properly and pyserial-asyncio is receiving in my case only first letter of response.
Have you manage to solve the problem all by yourself?

**Comment by bsdis** [comment]
Actually, i believe i have after very long testing and searching.
It seems to be a well preserved secret, but at least on linux I have to use a special incantation which tells the serial port to have a minimum character limit to have a blocking capability. The incantation looks like so:
stty -F /dev/ttyACM0 115200 line 0 min 1 time 0
Alternatively this incantation should also work
stty -F /dev/ttyACM0 raw

Now, welcome to the inner circle of serial communication magicians :) (hopefully)
