### ISSUE TITLE
How would you pass parameters to generator returned from create_serial_connection()

### ISSUE THREAD

**Issue by the-moog** [pyserial/pyserial-asyncio#41]
e.g.
```python
class MyProt(asyncio.Protocol)
    #BlahBlahBlah

loop = asyncio.get_event_loop()
prot = serial_asyncio.create_serial_connection(loop, MyProt, port, baudrate, myParam)
loop.run_until_complete(prot)
```
At this point I can't find a way to interact with bert and other parametrs such as `MyParam` are passed to pyserial.  Is there a proper way to pass parameters to the creation of the MyProt instance that is done internally by asyncio?

I would like to be able to supply `myParam` or do something like `bert.set_feature()` but that does not work due to the way asyncio works.

I've tried hacking it with
```python
_prot = prot.gi_frame.f_locals['args'][1]
_prot.set_feature(_prot, feature)
```
But that access the unbound `MyProt` rather than the running `prot`.

**Comment by d21d3q** [comment]
Like [this](https://github.com/d21d3q/pymodbus/blob/2a42e95d4fb79e4b87c123caf2f29b815459b50a/examples/contrib/asynchronous-asyncio-serial-client.py#L107). 
You are providing factory so anything that it will be called and return Protocol class.

**Comment by the-moog** [comment]
> 
> 
> Like [this](https://github.com/d21d3q/pymodbus/blob/2a42e95d4fb79e4b87c123caf2f29b815459b50a/examples/contrib/asynchronous-asyncio-serial-client.py#L107).
> You are providing factory so anything that it will be called and return Protocol class.

Thanks I'll look at that.
As pymodbus is a different package perhaps the docs for pyserial-asyncio should be updated with a more complete example?

**Comment by d21d3q** [comment]
Actually it is called factory [https://pyserial-asyncio.readthedocs.io/en/latest/api.html#serial_asyncio.create_serial_connection](here). 
I provided this example because it was the quickest one to provide recall

**Comment by the-moog** [comment]
Thanks, my code now looks like this and works (for others to follow)

```python
class MyProt(asyncio.Protocol)
    def __init__(self, param, *args, **kw):
        super().__init__(*args, **kw)
        self.param = param
        #BlahBlahBlah

def myprot_factory():
   return MyProt(myParam)

loop = asyncio.get_event_loop()
prot = serial_asyncio.create_serial_connection(loop, myprot_factory, port, baudrate)
loop.run_until_complete(prot)
```
