### ISSUE TITLE
`open_serial_connection` doesn't appear in the API documentation

### ISSUE THREAD

**Issue by adamhammes** [pyserial/pyserial-asyncio#43]
Thank you for this project! It's been a huge help.

I read about the `open_serial_connection` function in a [blog post about this library](https://tinkering.xyz/async-serial/), and have started using it in my project. However, it doesn't seem to appear in the [project's API documentation](https://pyserial-asyncio.readthedocs.io/en/latest/api.html#).

Was this omission intentional? If not, I'd love to help in adding the function to your docs.

Cheers!

**Comment by septatrix** [comment]
I also believe that the documentation is a bit lackluster at the moment. I for one would be very thankful if the API was described better and think that a PR would be merged if you made one.

**Comment by rob-smallshire** [comment]
PR #63 addresses this and other documentation issues.
