### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by mkeyno** [pyserial/pyserial-asyncio#47]
Hi
I've been trying to periodically write back data to a serial port, but it throws the following issue
AttributeError: 'NoneType' object has no attribute 'write'
any help is really appreciated 

```python
import asyncio
import serial_asyncio
import codecs


_reader=_writer=None 



async def SerialReader(loop):
    global _reader,_writer
    _reader,_writer = await serial_asyncio.open_serial_connection(url='COM7', baudrate=57600,loop=loop)
    while True:
            line = await _reader.readline()
            print(codecs.encode(line, 'base64'))
            
async def serialWriteLoop(writer,f):
    message =b'>*>p0x0800'
    while True:
        print(b'>*>p0x0800')
        for b in message:
            writer.write(bytes([b]))
        await asyncio.sleep(1/f);
        
loop = asyncio.new_event_loop();
asyncio.set_event_loop(loop)#
loop.run_until_complete(asyncio.gather(SerialReader(loop),serialWriteLoop(_writer,1)))
loop.run_forever() 
loop.close()


```

**Comment by d21d3q** [comment]
You have to remember, that asyncio code runs on one thread, so only one task is being executed at a time, and it can "switch" to another when you call `await` (yield).
So when you call `loop.run_until_complete(asyncio.gather(SerialReader(loop),serialWriteLoop(_writer,1)))`, then two tasks are being thrown on event loop. I am not sure which one is being executed as first, but lets assume that `SerialReader`. On second line of `SerialReader` there is `await` which creates new task (`open_serial_connection`) which is being added to event loop, to be executed later, and event loop can pick another task, for example `serialReader` (I am not sure if it will pick `serialReader` or `open_serial_connection`) but if it will enter `serialReader`, then it will go straight to `writer.write()` which is still `None`.
To make it working, you have to use some [synchronization](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Event)

**Comment by d21d3q** [comment]
@mkeyno, did it help you to solve that problem?

**Comment by mkeyno** [comment]
@d21d3q thanks for your concern, actually my project is more complicate than this and I'm using multithreading as well, I didn't get the proper result from async serial, thus I switch back to blocking serial
