### ISSUE TITLE
create_serial_connection() got multiple values for keyword argument 'loop'"

### ISSUE THREAD

**Issue by potens1** [pyserial/pyserial-asyncio#5]
if loop argument is already passed, it should be removed of kwargs, or if not passed, add it to kwargs and remove it from explicitly passing it
https://github.com/pyserial/pyserial-asyncio/blob/master/serial_asyncio/__init__.py#L398

**Comment by potens1** [comment]
Not able to reproduce again, I'll close my self the issue since it should come from bad manipulation from my side

**Comment by rob-smallshire** [comment]
Just as a note for anyone else arriving here, loop is using a new Python feature called 'keyword-only arguments'. It's an error to pass loop as a positional argument.
