### ISSUE TITLE
Write() does not do a genuine async write

### ISSUE THREAD

**Issue by wolfmanjm** [pyserial/pyserial-asyncio#53]
Strictly speaking the write() does not do a real async write if the write buffer is empty. Even though the serial.write() is non blocking, doing a real write there is technically incorrect IMO.

In addition as there is a bug in the posix serial.write() where writing to a port that is not ready will cause it to enter a tight loop continously throwing an EAGAIN exception, so we end up effectively with a blocking write. See https://github.com/pyserial/pyserial/issues/280.

The code I modified (and use) [here](https://github.com/wolfmanjm/kivy-smoothie-host/blob/master/libs/serial_asyncio/serial_asyncio.py#L113) does a real async write (every write gets buffered and executed asynchronously. This also avoids the aforementioned bug in serial.write().

If this is something you feel is the correct way to do it, let me know and I'll submit a PR.

I do undestand that issuing a genuine serial.write() if the buffer is empyy maybe more efficient so I could undersand why my solution may not be acceptible. (that is presuming the serial.write() bug is fixed). I have a workaround in the existing write() that I could submit that also avoids that bug, but keeps the instant write if the write buffer is empty.

**Comment by rob-smallshire** [comment]
Can you make a PR for this please?

**Comment by wolfmanjm** [comment]
Yes I'll do this ASAP. Been using it for a while now and it does the job nicely.

**Comment by rsippl** [comment]
Under heavy load, this issue (and the mentioned tight loop) is a show stopper. #56 works fine for me. Thanks, @wolfmanjm.
