### ISSUE TITLE
asyncio.coroutine deprecated in 3.8

### ISSUE THREAD

**Issue by teharris1** [pyserial/pyserial-asyncio#54]
Support for generator-based coroutines is deprecated as of 3.8 and is scheduled for removal in Python 3.10.

**Comment by rob-smallshire** [comment]
What are the implications of moving to `async def`? That we lose compatibility with Python versions prior to 3.5? I think that's entirely reasonable at this point.

**Comment by Adminiuga** [comment]
>  I think that's entirely reasonable at this point.
Second this

**Comment by Adminiuga** [comment]
Python 3.5 is EOL in two weeks. Python 3.4 EOL in 2019. IMO moving to `async def` is long overdue

**Comment by zsquareplusc** [comment]
pypistats lists downloads in the double digit percentages for Python 3.5 and practically none for 3.4. So refactoring that Python 3.5 is supported as minimal version should be fine.
