### ISSUE TITLE
How to send a string or integer through pyserial?

### ISSUE THREAD

**Issue by ChinmayStarFire** [pyserial/pyserial-asyncio#57]

**Comment by septatrix** [comment]
If you are asking general questions which are not related to the async functionality you should ask them at the main repository. 

However pyserial only supports sending binary data. This means that if you  wish to send strings or integers you need to encode them: `b"foobar"` (byte literal - can only contain ASCII), `"foobar".encode()` (you can pass an optional encoding) or for integers `str(42).encode()`...
