### ISSUE TITLE
Provide serial object via Transport.get_extra_info()

### ISSUE THREAD

**Issue by septatrix** [pyserial/pyserial-asyncio#62]
Currently the serial object can be accessed via the `.serial` property. However asyncio provides a prefered way to access information about the transport and the underlying resources which is [`BaseTransport.get_extra_info`](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.get_extra_info).

To align more closely to the stdlib I would like to have this implemented (or make a PR as it does not seem to hard). Personally I would also vote for deprecating the direct access property but I would also understand keeping it as a shorthand...

**Comment by rob-smallshire** [comment]
I'd happy to review and merge such a PR, with the usual caveat regarding the lack of my ability to publish to PyPI.
