### ISSUE TITLE
Can we get a release anytime soon? 

### ISSUE THREAD

**Issue by jabdoa2** [pyserial/pyserial-asyncio#64]
Last release is three years ago. Is it possible to get a release this or next year?

**Comment by rob-smallshire** [comment]
Dependent on @zsquareplusc who controls the PyPI credentials.

**Comment by rifoerster** [comment]
When i was thinking how to - while @zsquareplusc is busy - make use of the newest bugfixes i came across the following possibility of installing directly from git:
`pipenv install git+https://github.com/pyserial/pyserial-asyncio#egg=pyserial-asyncio`
(thought I'd share)

**Comment by jabdoa2** [comment]
Installing git master in a release is bad practice. Guess we will maintain our own fork in the future.

**Comment by rifoerster** [comment]
> 
> 
> Installing git master in a release is bad practice. 

I am curious on why that is. 
(pipenv will automatically note the used commit in the lock file (Pipfile.lock) to make sure that everyone's getting the same version, if potentially mismatching versions might be the problem)

**Comment by jabdoa2** [comment]
> > Installing git master in a release is bad practice.
> 
> I am curious on why that is.
> (pipenv will automatically note the used commit in the lock file (Pipfile.lock) to make sure that everyone's getting the same version, if potentially mismatching versions might be the problem)

Sure that would work but I prefer a release branch or tag over a pinned git commit. But not all our users use pipenv. Also we want to be able to install our framework next to other python packages which might use pyserial as well which causes more issues as python has a lot of issue when installing multiple versions of a package.

Long story short: We need a release or our users will run into issues.

**Comment by rob-smallshire** [comment]
[pyserial-asyncio 0.5](https://pypi.org/project/pyserial-asyncio/) has been released. Thank you @zsquareplusc.
