### ISSUE TITLE
StreamReader.read(n) returns incorrect amount of bytes

### ISSUE THREAD

**Issue by makupi** [pyserial/pyserial-asyncio#67]
I am continuously receiving 5 byte frames via. serial and created a task that is supposed to do just that, unfortunately sometimes the `.read(5)` returns less than 5 bytes. 
Am I doing something wrong or what is going on here? 
I verified the received data with a serial terminal and that looked good. 

My code is something like this:

```py
async def open(self):
    self.reader, self.writer = await serial_asyncio.open_serial_connection(
                url="/dev/ttyUSB0", baudrate=115200
            )

async def read_task(self):
    data = await self.reader.read(5)
    await self.process_data(data)
```

**Comment by geoffbrucepayne** [comment]
I'm having similar-sounding issues where I'm losing bytes.  In my case I'm interfacing to an AT command protocol with echo and certain bytes of the echo are being lost during read for example:
send_task `ATS80?\r`
receive_task `ATS8?\r\r\n`

The AT protocol also supports a CRC mode where replies have a suffix like `*ABCD\r\n` and I have tried reading 7 bytes I don't get all 7 bytes.

Manually testing using minicom I can see complete/expected responses in all cases.  I'm running at 9600 baud.

**Comment by rob-smallshire** [comment]
The [documentation](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamReader.read) for `StreamReader.read()` says "Read _up to_ n bytes." [my emphasis], not "Read exactly n bytes". Your code needs to be prepared for that fact that fewer than n bytes may be returned. The docstring in Python's source code says:

> If n is positive, this function try to read `n` bytes, and may return
> less or equal bytes than requested, but at least one byte. If EOF was
> received before any byte is read, this function returns empty byte
> object.

You could try [`StreamReader.readexactly()`](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamReader.readexactly) instead.
