### ISSUE TITLE
Never transmits on Windows in version 0.5

### ISSUE THREAD

**Issue by larsch** [pyserial/pyserial-asyncio#69]
[_ensure_writer](https://github.com/pyserial/pyserial-asyncio/blob/7623ac98121725fc31da8a1d18a7eb8ced705773/serial_asyncio/__init__.py#L308-L311)  just schedules [_poll_write](https://github.com/pyserial/pyserial-asyncio/blob/7623ac98121725fc31da8a1d18a7eb8ced705773/serial_asyncio/__init__.py#L302-L306) which never invokes _write_ready because serial.out_waiting is always zero.

**Comment by jabdoa2** [comment]
@larsch according to the docs `out_waiting` returns `the number of bytes in the output buffer`. I expected this to be the number of bytes available. Not 100% sure though. Might be as well the number of bytes used in the buffer. However, we shipped `0.4` of `pyserial-asyncio` to our MPF users and it seemed to have worked fine for all Windows users.

**Comment by jabdoa2** [comment]
Ok I found the culprit of that. Fixed that in #70 together with some other windows issues. As subtle behavior change in `0.5` exposed those bugs. My PR should fix them.

**Comment by Hedda** [comment]
@jabdoa2 Any plans for a quick bug-fix release? E.g. 0.5.2 or similar if using semantic versioning  https://semver.org or just 0.6?

**Comment by Hedda** [comment]
@zsquareplusc @rob-smallshire Is it possible for you to release 0.5.1 or 0.6 with bug-fix pyserial-asyncio as suggested in https://github.com/pyserial/pyserial-asyncio/pull/70 ? Serial writes is broken on Windows 10 with the 0.5 release of pyserial-asyncio. The workaround now is either downgrade pyserial-asyncio to 0.4 or manually install the master branch via Git.

**Comment by Hedda** [comment]
@zsquareplusc @rob-smallshire @septatrix @wolfmanjm Any chance you for a bug-fix release to resolve this issue on Windows?

**Comment by sean-marten** [comment]
@zsquareplusc @rob-smallshire Also just ran into this issue on Windows and would really appreciate a bug fix deploy sometime soon if possible, thanks!

**Comment by teharris1** [comment]
If this is fixed, can we get it published? This is a big deal for my module.

**Comment by teharris1** [comment]
Sorry meant to say "I can confirm the fix by @jabdoa2 fixed the issue." Can this fix be published?

**Comment by Carbenium** [comment]
@zsquareplusc I would like to chime in here as well. A release would be very much appreciated.

**Comment by Carbenium** [comment]
@bufferoverflow @zsquareplusc Just trying to raise some attention regarding this issue. The committed code works, just a new release is needed, so we can avoid patching the lib manually.

**Comment by serializingme** [comment]
I also can confirm that PR #70 fixed the problem. While the fixed version of the package doesn't get published, for those looking to install the fixed version you can leverage `pip` git support:
1. Make sure your environment doesn't have the installed version from pypi.org
2. Remove any entry for `pyserial-asyncio` in the `requirements.txt`
3. Add `git+https://github.com/pyserial/pyserial-asyncio.git@master` to the `requirements.txt` file

For manual installation:
```
pip uninstall pyserial-asyncio
pip install git+https://github.com/pyserial/pyserial-asyncio.git@master
```

Another option (which isn't as good), is to run the previous version (entry in `requirements.txt` is something along the lines of `pyserial-asyncio==0.4`) which doesn't have this issue. I did some tests and (for my usage) it works fine.

**Comment by Hedda** [comment]
> Another option (which isn't as good), is to run the previous version (entry in `requirements.txt` is something along the lines of `pyserial-asyncio==0.4`) which doesn't have this issue. I did some tests and (for my usage) it works fine.

Another option to whitelisting a specific version could be to use `'pyserial-asyncio!=0.5; platform_system=="Windows"'` entry in `requirements.txt` as then it should specifically blacklist version 0.5 for Windows as a platform only. 

Tip would be to also add a comment as why it was blacklisted, ex: `'pyserial-asyncio!=0.5; platform_system=="Windows"',  # 0.5 broke writes on Windows`

Problem with that is that you currently end up using different versions of pyserial-asyncio on different platforms

**Comment by jabdoa2** [comment]
> > Another option (which isn't as good), is to run the previous version (entry in `requirements.txt` is something along the lines of `pyserial-asyncio==0.4`) which doesn't have this issue. I did some tests and (for my usage) it works fine.
> 
> Another workaround option to whitelisting a specific version could be to use `'pyserial-asyncio!=0.5; platform_system=="Windows"'` entry in `requirements.txt` as then it should specifically blacklist version 0.5 for Windows as a platform only.
> 
> Tip would be to also add a comment as why it was blacklisted, ex: `'pyserial-asyncio!=0.5; platform_system=="Windows"', # 0.5 broke writes on Windows`
> 
> Problem with that is that you currently end up using different versions of pyserial-asyncio on different platforms

We currently ship exactly that workaround.

**Comment by teharris1** [comment]
> Problem with that is that you currently end up using different versions of pyserial-asyncio on different platforms

Specifically 0.5 has removed the `@coroutine` and moved to the more standard `async/await` approach. So I believe python 3.9 will break with <0.5

**Comment by scranen** [comment]
Tagging @bufferoverflow @zsquareplusc again, the latest released version has been broken on Windows for almost 10 months now while a fix is already merged :(

**Comment by rob-smallshire** [comment]
@scranen @jabdoa2 @Carbenium Given the unresponsiveness of the folks with the power to publish releases, I think you should seriously contemplate forking this project and publishing it to PyPI under a different name.

**Comment by jabdoa2** [comment]
Ok I will do that tonight under the missionpinball org

**Comment by zsquareplusc** [comment]
i've now added github actions and keys so that @rob-smallshire can make releases too

**Comment by zsquareplusc** [comment]
ah and i made a release (v0.6) and added a document on how to do this.

**Comment by bufferoverflow** [comment]
thanks @zsquareplusc !

**Comment by rob-smallshire** [comment]
This fixes has been released.
