### ISSUE TITLE
Upload a package to pypi

### ISSUE THREAD

**Issue by jabdoa2** [pyserial/pyserial-asyncio#9]
Can you upload a release to pypi? That will allow us to simplify our install instructions for users. Currently, users have to install it from git with pip manually. With a pypi package we could just add it as dependency in setup.py.

**Comment by rob-smallshire** [comment]
Yes. Coming soon!

**Comment by jabdoa2** [comment]
Is there a timeline for this yet? We (https://github.com/missionpinball/mpf) are planning our next release and depend on this. Otherwise we need provide additional instructions for users or upload it ourself.

**Comment by rob-smallshire** [comment]
`pyserial-asyncio` is now available on the PyPI at https://pypi.python.org/pypi/pyserial-asyncio
