### ISSUE TITLE
Multiple asyncio tasks writing to the same serial transport. Is it safe?

### ISSUE THREAD

**Issue by zapta** [pyserial/pyserial-asyncio#99]
When multiple asyncio tasks write packets to the serial transport. Is each packet guaranteed to be sent on the wire intact?  If it matters, we use only the asyncio default event loop.

We try to understand if we need to implement a synchronization on top of transport.write().

```
packet = bytearray(...)
transport.write(packet)
```

**Comment by katomaso** [comment]
It should be. Write method synchronously appends to a write buffer that will be dumped to the serial line at some point.

**Comment by zapta** [comment]
Thanks. That's very good. Closing.
